namespace PantryPlanner.Api.Features.Ingredients;

public static class DefaultIngredientCatalog
{
    public static readonly IReadOnlyList<string> All =
    [
        "Allspice",
        "Almonds",
        "Apple cider vinegar",
        "Apples",
        "Arugula",
        "Avocado",
        "Bacon",
        "Baking powder",
        "Baking soda",
        "Bananas",
        "Basil",
        "Bay leaves",
        "Beef chuck",
        "Beef stock",
        "Black beans",
        "Black pepper",
        "Blueberries",
        "Breadcrumbs",
        "Broccoli",
        "Brown sugar",
        "Butter",
        "Cabbage",
        "Carrots",
        "Cashews",
        "Cayenne pepper",
        "Cauliflower",
        "Celery",
        "Cheddar cheese",
        "Cherry tomatoes",
        "Chicken breasts",
        "Chicken stock",
        "Chicken thighs",
        "Chickpeas",
        "Chili powder",
        "Cilantro",
        "Cinnamon",
        "Cloves",
        "Coconut milk",
        "Coriander",
        "Corn",
        "Cream cheese",
        "Cucumber",
        "Cumin",
        "Curry powder",
        "Dijon mustard",
        "Dill",
        "Eggplant",
        "Eggs",
        "Feta",
        "Fish sauce",
        "Flour",
        "Garam masala",
        "Garlic",
        "Ginger",
        "Granulated sugar",
        "Green beans",
        "Green bell pepper",
        "Ground beef",
        "Heavy cream",
        "Honey",
        "Jalapeno",
        "Kale",
        "Ketchup",
        "Kidney beans",
        "Lemon",
        "Lentils",
        "Lettuce",
        "Lime",
        "Maple syrup",
        "Mayonnaise",
        "Milk",
        "Mozzarella",
        "Mushrooms",
        "Noodles",
        "Nutmeg",
        "Oats",
        "Olive oil",
        "Onion",
        "Orange",
        "Oregano",
        "Oyster sauce",
        "Paprika",
        "Parmesan",
        "Parsley",
        "Pasta",
        "Peanut butter",
        "Peanuts",
        "Penne",
        "Peas",
        "Poblano pepper",
        "Pork chops",
        "Potatoes",
        "Powdered sugar",
        "Quinoa",
        "Red bell pepper",
        "Red onion",
        "Red wine vinegar",
        "Rice",
        "Rice vinegar",
        "Rosemary",
        "Salmon",
        "Salt",
        "Sausage",
        "Scallions",
        "Sesame oil",
        "Shallot",
        "Shrimp",
        "Smoked paprika",
        "Sour cream",
        "Soy sauce",
        "Spaghetti",
        "Spinach",
        "Strawberries",
        "Sweet potatoes",
        "Tamari",
        "Thyme",
        "Tomato paste",
        "Tomato sauce",
        "Tomatoes",
        "Tuna",
        "Turmeric",
        "Vanilla extract",
        "Vegetable oil",
        "Vegetable stock",
        "Walnuts",
        "White wine vinegar",
        "Whole peeled tomatoes",
        "Yogurt",
        "Yellow onion",
        "Yeast",
        "Zucchini"
    ];
}
